Feature/routing service api
Pummas/graduate_work pull request #3
Opened 2023-03-31 09:37 UTC by Pummas

2023-03-31 14:23 UTC, RomanBorovskiy commented on routing_service_api/src/settings.py
> +    storage3_url: str = Field("http://localhost:9005/", env="STORAGE2_URL")
env="STORAGE3_URL" по логике

2023-03-31 14:23 UTC, RomanBorovskiy commented on routing_service_api/src/main.py
> +cdn_storages = []
не нашел использование в дальнейшем

2023-03-31 14:23 UTC, RomanBorovskiy commented on routing_service_api/src/main.py
> +    if cdn.check_file(obj_name):
проверяем только ближайшее хранилище? а если в другом чуть дальше есть этот файл? Логично тогда все по порядку перебрать

2023-03-31 14:23 UTC, RomanBorovskiy commented on routing_service_api/src/settings.py
> +    storages_count = 1
наверное для отладки только 1 стоит? в конфиге получается 3 хранилища...

2023-03-31 19:26 UTC, s-morichev requested changes
Желательно type hints добавить

2023-03-31 19:26 UTC, s-morichev commented on routing_service_api/src/settings.py
> +    storage1_ip: str = Field("83.220.236.105")
Хранилищ может быть несколько десятков и больше, лучше сразу использовать список для настроек хранилищ

2023-03-31 19:26 UTC, s-morichev commented on routing_service_api/src/storages.py
> +        return self.cdn_storages[min_dist_index]
Лучше возвращать отсортированный по расстоянию список и потом проверять наличие файла во всех хранилищах, начиная с ближайшего. Как пример
```
user_geo = geocoder.ip(ip_address)
storages = sorted(cdn_storages, key=lambda cdn: distance(geocoder.ip(cdn.ip).latlng, user_geo.latlng).km)
return storages
```

2023-04-01 19:28 UTC, Pummas commented on routing_service_api/src/main.py
> +    if cdn.check_file(obj_name):
В первом варианте таска была такая 
1.2. Ищет  ближайшее хранилище с нужным файлом

2023-04-01 19:28 UTC, Pummas commented on routing_service_api/src/settings.py
> +    storages_count = 1
Да, можно на 3 поменять)

2023-04-01 19:29 UTC, Pummas commented on routing_service_api/src/storages.py
> +        return self.cdn_storages[min_dist_index]
Надо еще их id куда-то писать
Но все еще опирался на минимальный функционал
1.2. Ищет  ближайшее хранилище с нужным файлом

2023-04-01 19:29 UTC, Pummas commented on routing_service_api/src/settings.py
> +    storage3_url: str = Field("http://localhost:9005/", env="STORAGE2_URL")
Да, не поправил

2023-04-01 19:29 UTC, Pummas commented on routing_service_api/src/main.py
> +cdn_storages = []
Забыл выпилить

2023-04-02 14:55 UTC, s-morichev approved these changes

2023-04-02 15:35 UTC, RomanBorovskiy commented on routing_service_api/src/main.py
> +    if cdn.check_file(obj_name):
Да, но сейчас получается - ищем ближайшее хранилище. Если в нем нет файла - отдаем из мастера (нулевого)

2023-04-03 06:40 UTC, merged

2023-04-03 14:29 UTC, valerycode reviewed
Хороший, понятный код.