Add admin panel for movies with S3 for uploading files
Pummas/graduate_work pull request #5
Opened 2023-04-01 17:56 UTC by valerycode

2023-04-01 19:32 UTC, Pummas commented on Makefile
>  	sleep 5  # ждем запуск постгрес для применения миграций
Вместо того, чтобы ждать 5 секунд можно на конфиг с базой повесить healthcheck, напишу ниже

2023-04-01 19:32 UTC, Pummas commented on docker-compose.yml
> +      - POSTGRES_DB=${PG_MOVIES_DB_NAME}
```
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
```

2023-04-02 15:54 UTC, s-morichev requested changes

2023-04-02 15:54 UTC, s-morichev commented on movies_admin/README.md
> +docker-compose exec admin_movies python manage.py migrate
Поддержку docker-compose обещают прекратить в июне https://docs.docker.com/compose/ Про разницу тут https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose

2023-04-02 15:54 UTC, s-morichev commented on movies_admin/README.md
> +docker-compose exec admin_notifications python manage.py collectstatic --no-input
admin_movies наверное

2023-04-03 06:43 UTC, merged

2023-04-10 15:18 UTC, valerycode commented on movies_admin/README.md
> +docker-compose exec admin_movies python manage.py migrate
Буду знать. Спасибо!

2023-04-10 15:19 UTC, valerycode commented on movies_admin/README.md
> +docker-compose exec admin_notifications python manage.py collectstatic --no-input
Да