Добавил запрос на получение списка хранилищ, добавил логику расчета ( Еще буду доделывать)
Pummas/graduate_work pull request #7
Opened 2023-04-08 11:36 UTC by Pummas

Добавил запрос на получение списка хранилищ, добавил логику расчета расстояние до хранилища

Добавил событие в UGC

2023-04-15 07:04 UTC, s-morichev requested changes
При запуске в докере сервис падает при любом запросе, надо поменять в докере команду запуска на CMD ["gunicorn", "src.main:app", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]

2023-04-15 07:04 UTC, s-morichev commented on cdn/routing_service/src/main.py
> +        response = requests.post(url, json=data)
Тут лучше отправлять асинхронный реквест, чтобы не блокировать выполнение

2023-04-15 07:04 UTC, s-morichev commented on cdn/routing_service/src/main.py
>      storage_worker.create_storage_list()
Нужно перенести перед if __name__ == "__main__" иначе воркер не создастя при запуске в докере

2023-04-15 07:04 UTC, s-morichev commented on cdn/routing_service/src/storages.py
> +            storages = get_example_storages()
Хорошо бы бэкофф добавить, а получение хранилищ  в  качестве примера толькко в debug режиме

2023-04-15 07:04 UTC, s-morichev commented on cdn/routing_service/src/main.py
> +                                )
Можно заранее создать список ObjectStorageBase, а не создавать новый экземпляр при каждом запросе. Например, храним этот список в StorageWorker, а в методе storage_worker.get_storages(ip_address) сразу выдаем отсортированный по растоянию список экземпляров ObjectStorageBase

2023-04-15 07:04 UTC, s-morichev commented on cdn/routing_service/src/main.py
> +@app.get("/get_media/{obj_name}")
Логичнее будет перенести ручку в api/v1

2023-04-16 16:44 UTC, valerycode approved these changes
По-моему, все отлично. Только в одном месте там не поняла(см. коммент).

2023-04-16 16:44 UTC, valerycode commented on cdn/routing_service/src/api/v1/media.py
> +    user_id = 1
А почему user_id=1? Может надо раскомментить строчки выше про токен?

2023-04-16 16:44 UTC, valerycode commented on cdn/routing_service/src/storages.py
> +                    ip=storage["ip_address"],
На будущее: было бы здорово предусмотреть кейс, что у каждого хранилища может быть своя уникальная пара access_key и secret_key

2023-04-16 16:44 UTC, valerycode commented on cdn/routing_service/src/core_model.py
> +    # orjson.dumps возвращает bytes, а pydantic требует unicode, поэтому декодируем
Можно убрать комменты:)

2023-04-16 21:14 UTC, Pummas commented on cdn/routing_service/src/core_model.py
> +    # orjson.dumps возвращает bytes, а pydantic требует unicode, поэтому декодируем
Пусть будут)

2023-04-16 21:15 UTC, Pummas commented on cdn/routing_service/src/storages.py
> +                    ip=storage["ip_address"],
Да, на будущее надо)

2023-04-16 21:15 UTC, Pummas commented on cdn/routing_service/src/api/v1/media.py
> +    user_id = 1
Забыл и так пульнул

2023-04-17 01:47 UTC, s-morichev approved these changes

2023-04-17 13:56 UTC, merged