Connect admin panel to load service
Pummas/graduate_work pull request #9
Opened 2023-04-15 20:51 UTC by valerycode

2023-04-16 09:46 UTC, s-morichev requested changes

2023-04-16 09:46 UTC, s-morichev commented on movies_admin/movies/models.py
> +            extension += letter
Если файл без расширения, то в качестве расширения будет зеркальное название файла. Другие сервисы ожидают названия файлов без расширения, просто id

2023-04-16 09:46 UTC, s-morichev commented on movies_admin/movies/tasks.py
> +            if (film.created + timedelta(hours=8)).strftime('%H:%M:%S') < datetime.now().strftime('%H:%M:%S'):
Нельзя ли тут сравнивать даты без преобразования в строки? И, наверное, нужно указать таймзону в datetime.now()

2023-04-16 09:46 UTC, s-morichev commented on cdn/load_service/src/api/v1/tasks.py
>      storage: str
В сервисе загрузки есть src/models для схем (в последнем коммите), логичнее перенести определения схем туда

2023-04-16 09:46 UTC, s-morichev commented on cdn/load_service/src/core/s3.py
> +        raise LoaderException(err)
Нужно возвращать что-то, что поймается проверкой `if "error" in result: raise TaskFailure(result)` в worker.py

2023-04-17 12:29 UTC, valerycode commented on movies_admin/movies/tasks.py
> +            if (film.created + timedelta(hours=8)).strftime('%H:%M:%S') < datetime.now().strftime('%H:%M:%S'):
Без преобразования не получится, так как в БД дата создания фильма хранится в формате "2023-04-17 12:11:26.938151**+00:00**" и из-за этого сравнение с текущей датой не работает корректно. Про таймзону спасибо!:) Забыла указать.

2023-04-17 14:13 UTC, valerycode commented on movies_admin/movies/models.py
> +            extension += letter
Поправила

2023-04-17 14:29 UTC, valerycode commented on cdn/load_service/src/core/s3.py
> +        raise LoaderException(err)
Done

2023-04-17 14:37 UTC, Pummas approved these changes

2023-04-17 15:02 UTC, merged